---
name: Mypy

defaults:
  run:
    # To load bashrc
    shell: bash -ieo pipefail {0}

on:
  pull_request:
    branches: [master, dev]

jobs:
  build:
    name: Mypy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          pip install .
          pip install types-setuptools
          pip install --upgrade mypy

          mkdir -p .github/linters
          cp pyproject.toml .github/linters

      - name: Mypy
        uses: docker://github/super-linter:v3
        if: always()
        env:
          # run linter on everything to catch preexisting problems
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Run only black
          VALIDATE_PYTHON_MYPY: true
          PYTHON_MYPY_CONFIG_FILE: pyproject.toml
